name: Deploy to Beta Channel

on:
  push:
    branches:
      - dev

jobs:
  deploy_beta_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.DEV_FIREBASE_SERVICE_ACCOUNT }}"
          projectId: dev-opportrain
          channelId: live
